### ISSUE TITLE
Test first gol version.

### ISSUE THREAD

**Issue by Josca** [PlainFormat/gol#2]
Test first gol version.
Can you install it?
Is it useful 4U? If not, why?
How to improve it?
How to extend it?
What should be changed?

**Comment by WestFlame** [comment]
Tested.

* Installs without problem.
* I like the git-like commands.
* Some kind of config file would be useful (at least with default filename for editing).
* I would like more intelligent addition of activities. Eg. If I add activity for current day, the program will scan the file and if there is already section for current day, the activity will be added under that section.

But very good start so far :).
